INSERT INTO department (department_name)
VALUES  (Engineering)
        (Finance)
        (Legal)
        (Sales)

INSERT INTO role (title, salary, department_name)
VALUES  (Sales Lead, 100000, Sales)
        (Salesperson, 80000, Sales)
        (Lead Engineer, 150000, Engineering)
        (Software Engineer, 120000, Engineering)
        (Account Manager, 160000, Finance)
        (Accountant, 125000, Finance)
        (Legal Team Lead, 250000, Legal)
        (0Lawyer, 190000, Legal)

INSERT INTO employee (first_name, last_name, title, department_name, salary, manager_id)
VALUES  (John, Doe, Sales Lead, Sales, 100000, null)
        (Mike, Chan, Salesperson, Sales, 80000, John Doe)
        (Ashley, Rodriguez, Lead Engineer, Engineering, 150000, null)
        (Kevin, Tupik, Software Engineer, Engineering, 120000, Ashley Rodriguez)
        (Kunal, Singh, Account Manager, Finance, 160000, null)
        (Malia, Brown, Accountant, Finance, 125000, Kunal Singh)
        (Sarah, Lourd, Legal Team Lead, Legal, 250000, null)
        (Tom Allen, Lawyer, Legal, 190000, Sarah Lourd)